DROP TABLE IF EXISTS PING;
DROP TABLE IF EXISTS CONFIGURATION;
DROP TABLE IF EXISTS PING_HISTORY;

CREATE TABLE PING(
CLIENT_ID VARCHAR(250) PRIMARY KEY ,
PING_TIMESTAMP BIGINT NOT NULL
);

CREATE TABLE PING_HISTORY(
ID INT AUTO_INCREMENT  PRIMARY KEY,
CLIENT_ID VARCHAR(250) NOT NULL,
PING_TIMESTAMP BIGINT NOT NULL
);



CREATE TABLE CONFIGURATION(  
ID INT AUTO_INCREMENT  PRIMARY KEY,
CONFIGURATION_NAME VARCHAR(250) NOT NULL,  
CONFIGURATION_VALUE  INT(8) NOT NULL
);



